### ISSUE TITLE
I can not use this plugin in my IDEA,what should I do?

### ISSUE THREAD

**Issue by CandyKIng1991** [ingokegel/jclasslib#56]
I can download this plug-in, but my idea does not display restart. After I restart, there is no show related menu in the view. My idea version is version 2020. I downloaded version 2020 on the official website and put it in the local plugin folder, but it is still invalid. Are there other configuration solutions to enable my plug-in to start?

**Comment by ingokegel** [comment]
> I downloaded version 2020 on the official website and put it in the local plugin folder,

You should install the plugin from the plugin manager.

>my idea does not display restart

I don't understand what that means

**Comment by WHZA** [comment]
I also have this problem.

![jclasslib](https://user-images.githubusercontent.com/44577765/134435777-452b3e36-c358-438b-b846-99bc154be7b6.gif)

The reason for the problem is that I clicked remove from sidebar under the show option menu in the sidebar.
Reinstalling the plug-in or even reinstalling IDEA doesn’t work. What should I do to make it redisplay?

**Comment by WHZA** [comment]
> I also have this problem.I have tried IDEA 2021.2.2 and 2020.2.4 and the corresponding plug-in version, all have this problem.

I tried it on another computer just now, but this error still occurs. It should not be a configuration problem.

**Comment by ingokegel** [comment]
I will fix the vanishing empty tool window if it's empty in the next version. You can show the tool window by opening a Java source editor and invoking "View->Show bytecode with jclasslib" from the menu,
